DROP TABLE IF EXISTS quiz CASCADE;
CREATE TABLE quiz (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  URL VARCHAR(2048) NOT NULL,
  content =
  answer =
);
