DROP TABLE IF EXISTS questions CASCADE;
CREATE TABLE questions (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  quiz_id INTEGER REFERENCES quiz(id) ON DELETE CASCADE,
  question1 VARCHAR(255) NOT NULL,
  question2 VARCHAR(255) NOT NULL,
  question3 VARCHAR(255),
  question4 VARCHAR(255),
  question5 VARCHAR(255)
);
